// questions.js — Bộ câu hỏi thi bằng lái xe
// Cấu trúc: { id, text, options:[{text,img?}], answer (0-based), explain, category, tags:[] }
// Dữ liệu mẫu 40 câu — Admin có thể mở rộng về sau

const DRIVING_QUESTIONS = [
  // ── BIỂN BÁO & QUY TẮC ──
  {id:1, cat:"Biển báo", text:"Biển báo nào sau đây có hình dạng tam giác, nền vàng, viền đỏ?", options:["Biển báo cấm","Biển báo nguy hiểm","Biển báo hiệu lệnh","Biển báo chỉ dẫn"], answer:1, explain:"Biển báo nguy hiểm có hình tam giác, nền vàng, viền đỏ để cảnh báo người lái xe về các nguy hiểm phía trước."},
  {id:2, cat:"Biển báo", text:"Biển báo cấm có hình dạng như thế nào?", options:["Hình tròn, nền trắng, viền đỏ","Hình tam giác, nền vàng","Hình vuông, nền xanh","Hình tròn, nền xanh"], answer:0, explain:"Biển báo cấm có hình tròn, nền trắng, viền đỏ. Người lái xe phải tuân thủ tuyệt đối các biển cấm."},
  {id:3, cat:"Biển báo", text:"Biển báo hiệu lệnh có đặc điểm nhận dạng nào?", options:["Hình tam giác nền vàng","Hình tròn nền xanh lam","Hình chữ nhật nền trắng","Hình tròn nền trắng viền đỏ"], answer:1, explain:"Biển báo hiệu lệnh có hình tròn, nền xanh lam, hình vẽ màu trắng, chỉ ra điều phải thực hiện."},
  {id:4, cat:"Biển báo", text:"Vạch kẻ đường màu vàng liền có ý nghĩa gì?", options:["Không được dừng xe","Không được vượt xe","Tốc độ tối đa 40km/h","Được phép quay đầu xe"], answer:1, explain:"Vạch kẻ đường màu vàng liền là vạch tim đường, cấm tất cả các loại xe vượt qua hoặc lấn sang phần đường đối diện."},
  {id:5, cat:"Biển báo", text:"Biển báo 'Đường một chiều' có ý nghĩa gì?", options:["Cấm ô tô đi vào","Xe chỉ được đi theo một chiều","Đường hẹp chỉ một làn xe","Cấm xe máy đi vào"], answer:1, explain:"Biển báo đường một chiều cho biết xe chỉ được phép đi theo chiều mà biển chỉ, không được đi ngược chiều."},
  // ── TỐC ĐỘ VÀ KHOẢNG CÁCH ──
  {id:6, cat:"Tốc độ", text:"Tốc độ tối đa của xe ô tô trên đường đô thị là bao nhiêu?", options:["40 km/h","50 km/h","60 km/h","80 km/h"], answer:1, explain:"Tốc độ tối đa cho phép xe ô tô trong khu vực đô thị là 50 km/h, trừ khi có biển báo khác."},
  {id:7, cat:"Tốc độ", text:"Trên đường cao tốc, tốc độ tối đa cho xe con là bao nhiêu?", options:["80 km/h","100 km/h","120 km/h","140 km/h"], answer:2, explain:"Trên đường cao tốc, tốc độ tối đa cho phép đối với xe ô tô con là 120 km/h và tối thiểu là 60 km/h."},
  {id:8, cat:"Tốc độ", text:"Khoảng cách an toàn tối thiểu khi đi 60 km/h là bao nhiêu mét?", options:["15 mét","25 mét","35 mét","45 mét"], answer:2, explain:"Ở tốc độ 60 km/h, khoảng cách an toàn tối thiểu giữa 2 xe là 35 mét để đảm bảo đủ thời gian phản ứng và phanh."},
  {id:9, cat:"Tốc độ", text:"Trong điều kiện sương mù dày, tầm nhìn dưới 50m, tốc độ tối đa là bao nhiêu?", options:["10 km/h","20 km/h","30 km/h","40 km/h"], answer:1, explain:"Khi sương mù dày, tầm nhìn dưới 50 mét, tốc độ không được vượt quá 20 km/h và phải bật đèn sương mù."},
  {id:10, cat:"Tốc độ", text:"Xe tải nặng trên đường ngoài đô thị có tốc độ tối đa là bao nhiêu?", options:["60 km/h","70 km/h","80 km/h","90 km/h"], answer:2, explain:"Xe tải nặng và xe khách trên đường ngoài đô thị có tốc độ tối đa là 80 km/h."},
  // ── XIN ĐƯỜNG VÀ NHƯỜNG ĐƯỜNG ──
  {id:11, cat:"Nhường đường", text:"Khi gặp xe ưu tiên (xe cứu thương, cứu hỏa, cảnh sát) đang hú còi, người lái xe phải làm gì?", options:["Tăng tốc vượt qua","Giảm tốc và nhường đường","Dừng hẳn lại bất kể vị trí","Đi sát lề trái"], answer:1, explain:"Khi gặp xe ưu tiên đang hú còi, người lái xe phải giảm tốc, đi sát về phía tay phải và nhường đường cho xe ưu tiên đi qua."},
  {id:12, cat:"Nhường đường", text:"Tại ngã tư không có tín hiệu đèn, không có biển báo, xe từ hướng nào được ưu tiên?", options:["Xe đi thẳng","Xe từ phía bên phải","Xe có kích thước lớn hơn","Xe đến trước"], answer:1, explain:"Tại ngã tư không có đèn tín hiệu và biển báo, xe từ phía bên phải được ưu tiên đi trước (quy tắc ưu tiên bên phải)."},
  {id:13, cat:"Nhường đường", text:"Khi xe đang lùi ra khỏi nhà, garage, người lái xe phải nhường đường cho ai?", options:["Xe đang đi trên đường","Chỉ nhường xe tải và xe buýt","Chỉ nhường người đi bộ","Không cần nhường vì đang lùi"], answer:0, explain:"Khi lùi ra khỏi nhà hay bãi đỗ xe, xe phải nhường đường cho tất cả xe và người đi bộ đang lưu thông trên đường."},
  {id:14, cat:"Nhường đường", text:"Tại vòng xuyến, xe nào được ưu tiên?", options:["Xe sắp vào vòng xuyến","Xe đang đi trong vòng xuyến","Xe lớn hơn","Xe đến trước"], answer:1, explain:"Xe đang lưu thông trong vòng xuyến được ưu tiên. Xe định vào vòng xuyến phải nhường đường và chỉ vào khi an toàn."},
  {id:15, cat:"Nhường đường", text:"Khi đèn tín hiệu màu vàng sáng lên, người lái xe phải làm gì?", options:["Tăng tốc để qua nhanh","Dừng trước vạch dừng nếu an toàn","Tiếp tục đi bình thường","Còi và đi qua"], answer:1, explain:"Đèn vàng cảnh báo đèn đỏ sắp tới. Nếu còn đủ khoảng cách an toàn, phải dừng xe trước vạch dừng. Nếu đã quá gần, được tiếp tục đi qua cẩn thận."},
  // ── SA HÌNH VÀ CẦM LÁI ──
  {id:16, cat:"Sa hình", text:"Khi thực hiện bài thi sa hình 'Dừng xe nhường đường người đi bộ', xe phải dừng cách vạch bao nhiêu?", options:["Không quá 1 mét","Không quá 0.5 mét","Không quá 2 mét","Đúng trên vạch"], answer:0, explain:"Khi dừng nhường đường người đi bộ, xe phải dừng trước vạch và không được cách vạch quá 1 mét."},
  {id:17, cat:"Sa hình", text:"Trong bài thi ghép xe vào nơi đỗ, xe có được chạm vào cọc tiêu không?", options:["Được chạm nhẹ 1 lần","Không được chạm vào cọc","Được chạm tối đa 2 lần","Chỉ được chạm cọc phía sau"], answer:1, explain:"Trong bài thi sa hình ghép xe, xe không được phép chạm vào cọc tiêu. Nếu chạm sẽ bị trừ điểm hoặc không đạt."},
  {id:18, cat:"Sa hình", text:"Bài thi 'Đường vuông góc' trong sa hình yêu cầu xe di chuyển qua mấy cổng?", options:["2 cổng","3 cổng","4 cổng","5 cổng"], answer:1, explain:"Bài thi đường vuông góc yêu cầu xe di chuyển qua 3 cổng hình chữ L, kiểm tra khả năng điều khiển tay lái trong không gian hẹp."},
  // ── ĐẠO ĐỨC VÀ AN TOÀN ──
  {id:19, cat:"An toàn", text:"Uống rượu bia bao nhiêu thì được phép lái xe?", options:["Dưới 0.25mg/lít khí thở","Dưới 0.05mg/ml máu","Không được lái xe nếu đã uống rượu bia","Uống ít thì được lái"], answer:2, explain:"Theo Luật giao thông đường bộ hiện hành, tuyệt đối không được lái xe khi đã uống rượu bia (nồng độ cồn bằng 0)."},
  {id:20, cat:"An toàn", text:"Khi lái xe, sử dụng điện thoại di động (không dùng thiết bị rảnh tay) có bị xử phạt không?", options:["Không, nếu chỉ nhắn tin ngắn","Có, bị xử phạt","Không, nếu đang dừng đèn đỏ","Chỉ bị nhắc nhở lần đầu"], answer:1, explain:"Sử dụng điện thoại di động khi lái xe (không dùng thiết bị rảnh tay) là vi phạm pháp luật và bị xử phạt tiền, tước bằng lái."},
  {id:21, cat:"An toàn", text:"Thắt dây an toàn khi lái xe là:", options:["Tùy chọn, không bắt buộc","Bắt buộc đối với ghế trước","Bắt buộc với tất cả người trên xe","Chỉ bắt buộc trên đường cao tốc"], answer:2, explain:"Tất cả người ngồi trên ô tô đều bắt buộc phải thắt dây an toàn. Vi phạm sẽ bị xử phạt."},
  {id:22, cat:"An toàn", text:"Xe ô tô phải bật đèn chiếu sáng khi nào?", options:["Chỉ ban đêm","Từ 18h đến 6h sáng","Khi tầm nhìn dưới 300m hoặc ban đêm","Chỉ khi trời tối hẳn"], answer:2, explain:"Xe phải bật đèn chiếu sáng từ 18h đến 6h sáng và cả khi ban ngày nếu tầm nhìn dưới 300m (sương mù, mưa to, bụi...)."},
  {id:23, cat:"An toàn", text:"Khi xe bị nổ lốp khi đang chạy tốc độ cao, người lái xe nên làm gì TRƯỚC TIÊN?", options:["Đạp phanh gấp","Giữ chặt vô lăng và giữ tay lái thẳng","Bẻ lái ngay sang lề","Tắt máy xe"], answer:1, explain:"Khi nổ lốp ở tốc độ cao, việc đầu tiên là giữ chặt vô lăng, giữ tay lái thẳng để kiểm soát xe, sau đó từ từ giảm tốc và dừng vào lề."},
  // ── PHÁP LUẬT GIAO THÔNG ──
  {id:24, cat:"Pháp luật", text:"Giấy phép lái xe hạng B1 có giá trị trong bao nhiêu năm?", options:["5 năm","10 năm","Vĩnh viễn","Không có thời hạn"], answer:2, explain:"Giấy phép lái xe hạng B1 (xe ô tô không kinh doanh vận tải) có giá trị sử dụng không thời hạn, không cần đổi định kỳ."},
  {id:25, cat:"Pháp luật", text:"Giấy phép lái xe hạng B2 có giá trị trong bao nhiêu năm?", options:["5 năm","10 năm","Vĩnh viễn","3 năm"], answer:0, explain:"Giấy phép lái xe hạng B2 (xe ô tô kinh doanh vận tải) có giá trị 5 năm và phải được đổi khi hết hạn."},
  {id:26, cat:"Pháp luật", text:"Vượt đèn đỏ bị phạt bao nhiêu tiền (xe ô tô)?", options:["200.000 - 400.000 đồng","400.000 - 600.000 đồng","4.000.000 - 6.000.000 đồng","1.000.000 - 2.000.000 đồng"], answer:2, explain:"Theo Nghị định 100/2019, lái xe ô tô vượt đèn đỏ bị phạt từ 4.000.000 đến 6.000.000 đồng và tước giấy phép lái xe 1-3 tháng."},
  {id:27, cat:"Pháp luật", text:"Dừng xe, đỗ xe trên cầu bị phạt bao nhiêu tiền (xe ô tô)?", options:["100.000 - 200.000 đồng","800.000 - 1.000.000 đồng","2.000.000 - 3.000.000 đồng","500.000 - 1.000.000 đồng"], answer:1, explain:"Dừng xe, đỗ xe trên cầu (trừ trường hợp bất khả kháng) bị phạt từ 800.000 đến 1.000.000 đồng."},
  // ── KỸ THUẬT LÁI XE ──
  {id:28, cat:"Kỹ thuật", text:"Khi xuống dốc dài và dốc đứng, nên làm gì để bảo vệ phanh?", options:["Đạp phanh liên tục","Về số thấp và phanh ngắt quãng","Tắt máy để xe tự trôi","Bơm phanh liên tục"], answer:1, explain:"Khi xuống dốc dài, nên về số thấp (phanh động cơ) và phanh ngắt quãng để tránh phanh bị nóng quá mức và mất tác dụng."},
  {id:29, cat:"Kỹ thuật", text:"Khi lái xe ban đêm, gặp xe đi ngược chiều, phải làm gì với đèn?", options:["Chuyển sang đèn pha (đèn chiếu xa)","Tắt hẳn đèn","Chuyển sang đèn cốt (đèn chiếu gần)","Nháy đèn liên tục"], answer:2, explain:"Khi gặp xe ngược chiều ở khoảng cách 150m (đường ngoài đô thị) hoặc 50m (trong đô thị), phải chuyển sang đèn cốt tránh lóa mắt xe ngược chiều."},
  {id:30, cat:"Kỹ thuật", text:"Xe đang đi vào đường ngoài đô thị, gặp đoạn đường bị ngập nước không rõ độ sâu, nên làm gì?", options:["Tăng tốc vượt qua nhanh","Đi thật chậm và quan sát","Dừng xe và tìm đường khác","Bấm còi và đi qua"], answer:1, explain:"Khi gặp đường ngập nước không rõ độ sâu, phải giảm tốc độ thật chậm, quan sát mực nước và đi cẩn thận. Nếu nước quá sâu (trên 30cm) nên tìm đường khác."},
  // ── HẠNG B — ĐẶC THÙ ──
  {id:31, cat:"Hạng B", text:"Giấy phép lái xe hạng B1 cho phép lái loại xe nào?", options:["Xe dưới 9 chỗ ngồi, không kinh doanh","Xe tải dưới 3.5 tấn","Cả xe con và xe tải nhỏ","Chỉ xe máy dưới 175cc"], answer:0, explain:"GPLX hạng B1 cho phép lái xe ô tô chở người đến 9 chỗ ngồi (kể cả lái xe), xe tải có khối lượng hàng hóa dưới 3500 kg dùng cho mục đích không kinh doanh."},
  {id:32, cat:"Hạng B", text:"Người có GPLX hạng B2 được phép lái xe nào sau đây?", options:["Xe buýt 30 chỗ","Xe ô tô chở người đến 9 chỗ ngồi","Xe container","Xe taxi 4 chỗ kinh doanh"], answer:3, explain:"GPLX hạng B2 cho phép lái xe ô tô đến 9 chỗ ngồi (kể cả lái xe) và xe tải đến 3500 kg dùng để kinh doanh vận tải."},
  {id:33, cat:"Hạng B", text:"Độ tuổi tối thiểu để thi lấy GPLX hạng B1 là bao nhiêu tuổi?", options:["16 tuổi","18 tuổi","20 tuổi","21 tuổi"], answer:1, explain:"Độ tuổi tối thiểu để thi lấy GPLX hạng B1 và B2 là 18 tuổi đủ."},
  // ── TÌNH HUỐNG THỰC TẾ ──
  {id:34, cat:"Tình huống", text:"Khi đang lái xe, bạn thấy trẻ em đang chạy ra đường, bạn phải làm gì?", options:["Bấm còi liên tục và tiếp tục đi","Giảm tốc độ ngay và chuẩn bị dừng hẳn","Bẻ lái tránh sang làn khác","Nháy đèn cảnh báo và giữ nguyên tốc độ"], answer:1, explain:"Khi phát hiện trẻ em đang chạy ra đường, phải lập tức giảm tốc độ và chuẩn bị dừng hẳn. Trẻ em thường không nhận thức được nguy hiểm và hành động khó đoán."},
  {id:35, cat:"Tình huống", text:"Xe bạn đột ngột mất phanh khi đang chạy, bạn nên làm gì?", options:["Tắt máy ngay lập tức","Về số thấp, dùng phanh tay từ từ, tìm chỗ an toàn để dừng","Lao vào lề đường ngay","Bẻ lái liên tục để giảm tốc"], answer:1, explain:"Khi mất phanh chân, cần bình tĩnh: về số thấp dần để phanh động cơ, kéo nhẹ phanh tay (không giật mạnh), tìm chỗ an toàn để dừng xe như lề đường hoặc dốc lên."},
  {id:36, cat:"Tình huống", text:"Khi qua đường sắt có rào chắn đang đóng, bạn phải làm gì?", options:["Đi chậm qua nhanh","Dừng lại và chờ rào chắn mở","Còi xin đường và đi qua","Lùi xe và tìm đường khác"], answer:1, explain:"Khi rào chắn đường sắt đang đóng, bắt buộc phải dừng xe và chờ. Tuyệt đối không được vượt rào chắn vì nguy cơ tai nạn rất cao."},
  {id:37, cat:"Tình huống", text:"Bạn đang đi trên đường, thấy tai nạn giao thông vừa xảy ra, bạn nên làm gì TRƯỚC TIÊN?", options:["Tiếp tục đi và gọi cho ai đó","Dừng xe an toàn, bật đèn khẩn cấp, gọi cấp cứu 115 và cảnh sát 113","Lấy điện thoại quay video","Hỏi người xung quanh xem có cần giúp không"], answer:1, explain:"Khi gặp tai nạn: dừng xe an toàn, bật đèn cảnh báo, gọi cấp cứu 115 và cảnh sát 113, bảo vệ hiện trường và sơ cứu nạn nhân nếu được."},
  {id:38, cat:"Tình huống", text:"Gặp xe cứu thương đang hú còi ở đường 2 làn không có dải phân cách, bạn phải làm gì?", options:["Tăng tốc và thoát khỏi khu vực","Đi sát về bên phải, nhường đường cho xe cứu thương","Dừng hẳn tại chỗ","Bẻ lái sang trái để tránh"], answer:1, explain:"Khi nghe xe ưu tiên hú còi, phải đi sát về phía tay phải đến mức có thể và nhường đường, không được chắn đường xe ưu tiên."},
  {id:39, cat:"Tình huống", text:"Trời mưa lớn, đường trơn, bạn cần điều chỉnh gì khi lái xe?", options:["Giảm tốc độ và tăng khoảng cách an toàn","Tăng tốc để vượt qua vùng mưa nhanh hơn","Giữ nguyên tốc độ bình thường","Đi gần lề đường hơn"], answer:0, explain:"Khi trời mưa và đường trơn, cần giảm tốc độ (tối thiểu 20% so với điều kiện bình thường) và tăng khoảng cách an toàn để bù cho việc quãng đường phanh tăng lên."},
  {id:40, cat:"Tình huống", text:"Khi đi vào đường hầm, bạn cần làm gì?", options:["Tắt đèn để không chói mắt xe ngược chiều","Bật đèn xe (đèn chiếu gần) và giảm tốc độ","Tăng tốc để qua nhanh","Không cần làm gì đặc biệt"], answer:1, explain:"Khi vào đường hầm, bắt buộc bật đèn xe (đèn chiếu gần) để nhìn thấy đường và để xe khác thấy bạn, đồng thời giảm tốc về tốc độ quy định trong hầm."}
];
